name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore .\RayTraceTest\raytracetest.cspro
    - name: Build
      run: dotnet build .\RayTraceTest\raytracetest.cspro --no-restore
    - name: Test
      run: dotnet test .\RayTraceTest\raytracetest.cspro --no-build --verbosity normal
